#include "LED.h"


 void LED_Init(void){
  
  GPIO_Init(LED_ON_OFF_PORT, LED_ON_OFF_PIN, GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED_MODE_PORT, LED_MODE_PIN, GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED_HCL_PORT, LED_HCL_PIN, GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED_TOMATO_PORT, LED_TOMATO_PIN, GPIO_MODE_OUT_PP_LOW_FAST);
  
  GPIO_Init(LED_BAR_1_7_PORT, LED_BAR_1_PIN | LED_BAR_2_PIN | LED_BAR_3_PIN | LED_BAR_4_PIN
            | LED_BAR_5_PIN | LED_BAR_6_PIN | LED_BAR_7_PIN, GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED_BAR_8_9_PORT, LED_BAR_8_PIN | LED_BAR_9_PIN , GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED_BAR_10_PORT, LED_BAR_10_PIN, GPIO_MODE_OUT_PP_LOW_FAST);
  
//  GPIO_Init(LED_PWM_C_PORT,LED_PWM_C_PIN,GPIO_MODE_OUT_PP_HIGH_FAST);
 // GPIO_Init(LED_PWM_W_PORT,LED_PWM_W_PIN,GPIO_MODE_OUT_PP_HIGH_FAST);

}
 void LED_tonggle(void){
  for(int i = 0; i < 10; i++){
    GPIO_WriteReverse(LED_ON_OFF_PORT, LED_ON_OFF_PIN);
    GPIO_WriteReverse(LED_MODE_PORT, LED_MODE_PIN);
    GPIO_WriteReverse(LED_HCL_PORT, LED_HCL_PIN);
    GPIO_WriteReverse(LED_TOMATO_PORT, LED_TOMATO_PIN);
    
    GPIO_WriteReverse(LED_BAR_1_7_PORT, LED_BAR_1_PIN | LED_BAR_2_PIN | LED_BAR_3_PIN | LED_BAR_4_PIN
            | LED_BAR_5_PIN | LED_BAR_6_PIN | LED_BAR_7_PIN);
    GPIO_WriteReverse(LED_BAR_8_9_PORT, LED_BAR_8_PIN | LED_BAR_9_PIN);
    GPIO_WriteReverse(LED_BAR_10_PORT, LED_BAR_10_PIN);
    Fn_DELAY_Long(1000);
  }
}

void LED_PWM_Config(void){
  /* Time base configuration */
  TIM2_TimeBaseInit(TIM2_PRESCALER_8, 999);

  /* PWM1 Mode configuration: Channel1 */ 
  TIM2_OC1Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE,499, TIM2_OCPOLARITY_HIGH);
  TIM2_OC1PreloadConfig(ENABLE);

  /* PWM1 Mode configuration: Channel2 */ 
 // TIM2_OC2Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE,250, TIM2_OCPOLARITY_HIGH);
 // TIM2_OC2PreloadConfig(ENABLE);

  /* PWM1 Mode configuration: Channel3 */         
 TIM2_OC3Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE,499, TIM2_OCPOLARITY_HIGH);
 TIM2_OC3PreloadConfig(ENABLE);

  TIM2_ARRPreloadConfig(ENABLE);

  /* TIM2 enable counter */
  TIM2_Cmd(ENABLE);
  TIM2_SetCompare1(0);
  TIM2_SetCompare3(0);
}